// apps/react-akita-app/src/app/todos/TodosPage.tsx
import React from 'react';
import { AddTodo } from './AddTodo';
import { Filters } from './Filters';
import { TodoList } from './Todos';
import { untilDestroyed } from '../take-until';
import { todosService } from './state/todos.service';
import { todosQuery } from './state/todos.query';
import { Todo } from './state/todo.model';
import { ID } from '@datorama/akita';

export class TodosPageComponent extends React.PureComponent {
  state: { todos: Todo[]; filter: string } = { todos: [], filter: '' };

  constructor(props) {
    super(props);
  }

  add = (text: string) => todosService.add(text);

  toggleTodo = (id: ID) => todosService.complete(id);

  deleteTodo = (id: ID) => todosService.delete(id);

  changeFilter = ({ target: { value } }) => {
    todosService.updateFilter(value);
  };

  componentDidMount() {
    todosQuery.selectVisibleTodos$.pipe(untilDestroyed(this)).subscribe(todos => this.setState({ todos }));

    todosQuery.selectVisibilityFilter$.pipe(untilDestroyed(this)).subscribe(filter => this.setState({ filter }));
  }

  render() {
    return (
      <div className="padding">
        <AddTodo add={this.add} />
        <TodoList todos={this.state.todos} toggleTodo={this.toggleTodo} onDelete={this.deleteTodo} />
        <Filters onChange={this.changeFilter} active={this.state.filter} />
      </div>
    );
  }
}

// packages/ng-playground/src/app/todos-app/todos-page/todos-page.component.ts
import { Component, OnInit } from '@angular/core';
import { EntityStateHistoryPlugin, ID, isUndefined, StateHistoryPlugin } from '@datorama/akita';
import { map, Observable } from 'rxjs';
import { initialFilters, VISIBILITY_FILTER } from '../filter/filter.model';
import { Todo } from '../state/todo.model';
import { TodosQuery } from '../state/todos.query';
import { TodosService } from '../state/todos.service';

@Component({
  selector: 'app-todos-page',
  templateUrl: './todos-page.component.html',
  styleUrls: ['./todos-page.component.css'],
})
export class TodosPageComponent implements OnInit {
  todos$: Observable<Todo[]>;
  activeFilter$: Observable<VISIBILITY_FILTER>;

  filters = initialFilters;
  checkAll$: Observable<boolean>;
  stateHistory: StateHistoryPlugin;
  stateHistoryEntity: EntityStateHistoryPlugin;

  constructor(private todosQuery: TodosQuery, private todosService: TodosService) {}

  ngOnInit() {
    this.todos$ = this.todosQuery.selectVisibleTodos$;
    this.activeFilter$ = this.todosQuery.selectVisibilityFilter$;
    this.checkAll$ = this.todosQuery.checkAll$.pipe(map((numCompleted) => numCompleted && numCompleted === this.todosQuery.getCount()));
    this.stateHistory = new StateHistoryPlugin(this.todosQuery);
    this.stateHistoryEntity = new EntityStateHistoryPlugin(this.todosQuery);
  }

  moveUp(index: number) {
    this.todosService.move(index);
  }

  undo(id?) {
    if (isUndefined(id)) {
      this.stateHistory.undo();
    } else {
      this.stateHistoryEntity.undo(id);
    }
  }

  redo(id?) {
    if (isUndefined(id)) {
      this.stateHistory.redo();
    } else {
      this.stateHistoryEntity.redo(id);
    }
  }

  add(input: HTMLInputElement) {
    this.todosService.add(input.value);
    input.value = '';
  }

  complete(todo: Todo) {
    this.stateHistory.ignoreNext();
    this.todosService.complete(todo);
  }

  complete2(event, todo: Todo) {
    const _todo = { ...todo, completed: event.target.checked };
    this.todosService.complete(_todo);
  }

  delete(id: ID) {
    this.todosService.delete(id);
  }

  changeFilter(filter: VISIBILITY_FILTER) {
    this.todosService.updateFilter(filter);
  }

  checkAll({ target }) {
    this.todosService.checkAll(target.checked);
  }

  trackBy(_, todo) {
    return todo.id;
  }
}
